config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'restaurants#index'

  resources :restaurants do
    collection do
      get 'featured'
    end

    member do
      get 'chef'
    end

    resources :reviews, only: [:index, :new, :create]
  end

  # delete '/reviews/:id'
  resources :reviews, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates :name, presence: true

  has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  # filter
  # before_action :<method_name>, except: [:<action1>]
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def featured
    # up to you
    @featured_restaurants = Restaurant.where(rating: 5)
  end

  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def new
    @new_restaurant = Restaurant.new
  end

  def create
    @new_restaurant = Restaurant.new(strong_params)

    if @new_restaurant.save
      redirect_to show_restaurant_path(@new_restaurant)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @restaurant.update(strong_params)
      redirect_to show_restaurant_path(@restaurant)
    else
      render :edit
    end
  end

  def destroy
    if @restaurant.destroy
      redirect_to restaurants_path
    end
  end


  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def strong_params
    params.require(:restaurant).permit(:name, :rating, :address, :chef_name)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def index
    @restaurant = Restaurant.find(params[:restaurant_id])
    @reviews = Review.where(restaurant: @restaurant)
    @new_review = Review.new
  end

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @new_review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @reviews = Review.where(restaurant: @restaurant)
    @new_review = Review.new(review_params)
    @new_review.restaurant = @restaurant

    if @new_review.save
      redirect_to restaurant_reviews_path(@restaurant)
    else
      render :index
    end

  end

  def destroy
  end

  private

  def review_params
    params.require(:review).permit(:content)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ThespoonWithActiverecord</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- you want to make your site responsive -->
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for restaurant do |f|%>
  <%= f.input :name %>
  <%= f.input :rating %>
  <%= f.input :address %>
  <%= f.input :chef_name %>

  <%= f.button :submit, class: 'btn btn-primary' %>
<% end %>

app/views/restaurants/edit.html.erb
<%= render 'form', restaurant: @restaurant %>

app/views/restaurants/featured.html.erb
<div class="cards">
  <% @featured_restaurants.each do |resto| %>
  <div class="card">
    <img src="https://source.unsplash.com/400x300/?restaurant,<%= resto.name %>" class="card-img-top" alt="<%= resto.name %>">
    <div class="card-body">
      <h5 class="card-title"><%= resto.name %></h5>
      <p class="card-text">Chef: <%= resto.chef_name %></p>
      <%= link_to 'View', resto, class: "btn btn-primary" %>
      <%= link_to 'Delete', restaurant_path(resto), method: :delete, class: "btn btn-warning" %>
    </div>
  </div>
  <% end %>
</div>

app/views/restaurants/index.html.erb
<ul>
  <% @restaurants.each do |resto| %>
  <li>
    <h2>
      <%= resto.name %>
    </h2>
    <p>
      <%= resto.created_at %>
    </p>
    <%= link_to 'delete', destroy_restaurant_path(resto), method: :delete %>

  </li>
  <% end %>
</ul>

app/views/restaurants/new.html.erb
<%= render 'form', restaurant: @new_restaurant %>

app/views/restaurants/show.html.erb
<h2>
  <%= @restaurant.name %>
</h2>
<p>
  <%= @restaurant.created_at %>
</p>

<%= link_to 'Edit this restaurant', edit_restaurant_path(@restaurant) %><br>
<%= link_to "Find out more about #{@restaurant.chef_name}", chef_restaurant_path(@restaurant) %>

app/views/reviews/index.html.erb
<ul>
  <% @reviews.each do |review| %>
  <li><%= review.content %></li>
  <% end %>
</ul>

<%= simple_form_for [@restaurant, @new_review] do |f| %>
  <%= f.input :content %>
  <%= f.button :submit, class: 'btn btn-primary btn-block' %>
<% end %>

app/views/reviews/new.html.erb
<h2>Create new review here</h2>

<%= simple_form_for [@restaurant, @new_review] do |f| %>
  <%= f.input :content %>
  <%= f.button :submit, class: 'btn btn-primary btn-block' %>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to 'The Spoon', root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item <%= current_page?(root_path) && 'active' %>">
        <%= link_to 'Home', root_path, class: 'nav-link' %>
      </li>
      <li class="nav-item <%= current_page?(featured_restaurants_path) && 'active' %>">
        <%= link_to 'Featured', featured_restaurants_path, class: 'nav-link' %>
      </li>
    </ul>
  </div>
</nav>